<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Curd Operation.aspx.cs" Inherits="Curd_Operation.Curd_Operation" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <style type="text/css">
        .auto-style1 {
            width: 100%;
        }
        .auto-style2 {
            height: 133px;
        }
    </style>
</head>
<body>
     
        <div  style="font-weight:bold;font-size:xx-large; color:aquamarine"  align="center">
            Curd Operations In ASP.NET 
            </div>
    <form id="frm" runat="server">
        <div>
            <table style="font-size: x-large; font-weight: bold; color: #990033" align ="center" >
                <tr>
                    <td>
                        <asp:Label ID="lblId" runat="server" Text="EmployeeID" ></asp:Label>
                    </td>
                    <td>
                        <asp:TextBox ID="txtId" runat="server"  ReadOnly="false"></asp:TextBox>
                    </td>
                </tr>
                <tr>
                    <td>
                        <asp:Label ID="lblName" runat="server" Text="EmployeeName" Font-Size="Medium" ForeColor="Black"></asp:Label>
                    </td>
                    <td>
                        <asp:TextBox ID="txtName" runat="server" ></asp:TextBox>
                    </td>
                </tr>
                <tr>
                    <td>
                        <asp:Label ID="lblCity" runat="server" Text="EmployeeCity" Font-Size="Medium" ForeColor="Black"></asp:Label>
                    </td>
                    <td>
                        <asp:TextBox ID="txtCity" runat="server"></asp:TextBox>
                        <%--<asp:DropDownList ID="ddlCity" runat="server">
                            <asp:ListItem>Andhra Pradesh</asp:ListItem>
                            <asp:ListItem>Telangana</asp:ListItem>
                            <asp:ListItem>Anthatapuramu</asp:ListItem>
                            <asp:ListItem>Kurnool</asp:ListItem>
                            <asp:ListItem>Benguluru</asp:ListItem>
                            <asp:ListItem>Chennai</asp:ListItem>
                            <asp:ListItem>Vizag</asp:ListItem>
                        </asp:DropDownList>--%>
                    </td>
                </tr>
                <tr>
                    <td>
                        <asp:Label ID="lblAge" runat="server" Text="EmployeeAge" Font-Size="Medium" ForeColor="Black"></asp:Label>
                    </td>
                    <td>
                        <asp:TextBox ID="txtAge" runat="server"></asp:TextBox>
                    </td>
                </tr>
                <%--<tr>
                    <td>
                        <asp:Label ID="lblSex" runat="server" Text="EmployeeSex" Font-Size="Medium" ForeColor="Black"></asp:Label>
                    </td>
                    <td>
                        <asp:RadioButtonList ID="rblSex" runat="server"  RepeatDirection="Horizontal" ForeColor="Black">
                            <asp:ListItem>Male</asp:ListItem>
                            <asp:ListItem>Female</asp:ListItem>
                        </asp:RadioButtonList>
                    </td>
                </tr>--%>
                <tr>
                    <td>
                        <asp:Label ID="lblJoiningDate" runat="server" Text="Joining Date" Font-Size="Medium" ForeColor="Black"></asp:Label>
                    </td>
                    <td>
                        <asp:TextBox ID="txtJoiningDate" runat="server" ></asp:TextBox>
                    </td>
                </tr>
                <tr>
                    <td>
                        <asp:Label ID="lblContact" runat="server" Text="Contact" Font-Size="Medium" ForeColor="Black"></asp:Label>
                    </td>
                    <td>
                        <asp:TextBox ID="txtContact" runat="server"></asp:TextBox>
                    </td>
                </tr>
                <tr>
                    <td colspan="2" align="center">
                        <asp:Button ID="btnInsert" runat="server" Text="Insert" OnClick="btnInsert_Click" />
&nbsp;&nbsp;
                        <asp:Button ID="btnUpdate" runat="server"  Text="Update" OnClick="btnUpdate_Click" />
&nbsp;&nbsp;&nbsp;
                        <asp:Button ID="btnDelete" runat="server" Text="Delete" OnClick="btnDelete_Click" />
&nbsp;&nbsp;
                        <asp:Button ID="btnView" runat="server" Text="View" OnClick="btnView_Click" />
                    </td>
                </tr>
            </table>
        </div>

        <div>
            
            <asp:GridView ID="gvDetails"  runat="server" BackColor="LightGoldenrodYellow" BorderColor="Tan" BorderWidth="1px" CellPadding="2" ForeColor="Black" GridLines="None" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" OnRowDeleting="gvDetails_RowDeleting" OnSelectedIndexChanged="gvDetails_SelectedIndexChanged">
                <AlternatingRowStyle BackColor="PaleGoldenrod" />
                <FooterStyle BackColor="Tan" />
                <HeaderStyle BackColor="Tan" Font-Bold="True" />
                <PagerStyle BackColor="PaleGoldenrod" ForeColor="DarkSlateBlue" HorizontalAlign="Center" />
                <SelectedRowStyle BackColor="DarkSlateBlue" ForeColor="GhostWhite" />
                <SortedAscendingCellStyle BackColor="#FAFAE7" />
                <SortedAscendingHeaderStyle BackColor="#DAC09E" />
                <SortedDescendingCellStyle BackColor="#E1DB9C" />
                <SortedDescendingHeaderStyle BackColor="#C2A47B" />
            </asp:GridView>
        </div>
        </form>
        
</body>
</html>
