//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task1
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentInfoBasic_1
    {
        public int StudentId { get; set; }
        public string Name { get; set; }
        public string Subjects { get; set; }
        public Nullable<int> Marks { get; set; }
        public string PhoneNumber { get; set; }
        public string MailId { get; set; }
    }
}
